### ISSUE TITLE
Refactor-given-todo-app

### ISSUE THREAD

**Issue by danielkull** [danielkull/todo-app-with-cypress#1]
# Refactor Todo App

Refactor the [example todo app](https://github.com/coding-bootcamps-eu/todo-app) (or use your own Todo App) to use JS Modules.

- [ ] Use JS Modules
- [ ] Avoid global code
- [ ] Split your app into a `app.js` and `lib.js``
- [ ] Try to refactor existing functions into pure functions
