### ISSUE TITLE
jest-and-example-todo-app

### ISSUE THREAD

**Issue by danielkull** [danielkull/todo-app-with-cypress#3]
# Jest and example Todo App

Refactor the [example todo app](https://github.com/coding-bootcamps-eu/todo-app) and use Jest to create a Unit Test.

> Tutorial on how to use Jest with ES Modules: https://how-to.dev/how-to-set-up-jest-for-es-module

- [x] Install the necessary dependencies
  - [x] #4
  - [x] Jest (`npm i --save-dev jest`)
  - [x] Jest typings (`npm i --save-dev @types/jest`)
  - [x] Babel Plugin that transforms ES Modules (`npm install --save-dev @babel/plugin-transform-modules-commonjs`)
- [x] Create a Babel config (`.babelrc`) to use the Plugin (see code below) 
- [x] Create a Jest config (`jest.config.js`) that ignores the cypress tests
- [x] Edit package.json. Add in script a test to open jest
- [x] Create a unit test for the `checkDuplicate` function
- [x] Refactor the `checkDuplicate` function to be a pure function (it currently accesses a global variable)

> Only test functions without DOM access

.babelrc
```
{
  "env": {
    "test": {
      "plugins": ["@babel/plugin-transform-modules-commonjs"]
    }
  }
}
```

jest.config.js
```js
const config = {
  testPathIgnorePatterns: ["/node_modules/", "/cypress/"],
};

module.exports = config;
```

edit package.json
```js
{
...
"scripts": {
    "test": "jest"
}
...
}
```

Use the refernce tag for IntelliSense in VSCode.
```js
/// <reference types="jest />

// Your test
```
